import type { AdminQuotation } from "./columns";
import type { ReactNode } from "react";

export const dummyQuotations: AdminQuotation[] = [
  {
    teacherName: "Teacher Name",
    email: "teacher@example.com",
    phone: "1234567890",
    id: "317",
    requestedAt: "2026-01-21T17:38:00",
    schoolName: "Abbeystrewry NS",
    from: "Abbeystrewry National School, Castletownsend Road, Carrigfadda, Skibbereen, County Cork, Ireland",
    to: "Wild Atlantic Pool and Fitness Centre, Baltimore, Skibbereen, County Cork, Ireland",
    tripDate: "2026-02-12T11:00:00",
    passengers: 35,
    price: 260.0,
    status: "Pending",
    type: "Return",
  },
  {
    teacherName: "Teacher Name",
    email: "teacher@example.com",
    phone: "1234567890",
    id: "316",
    requestedAt: "2026-01-21T17:37:00",
    schoolName: "Abbeystrewry NS",
    from: "Abbeystrewry National School, Castletownsend Road, Carrigfadda, Skibbereen, County Cork, Ireland",
    to: "Bandon, County Cork, Ireland",
    tripDate: "2025-09-25T09:30:00",
    passengers: 39,
    price: 300.0,
    status: "Pending",
    type: "Return",
  },
  {
    teacherName: "Teacher Name",
    email: "teacher@example.com",
    phone: "1234567890",
    id: "315",
    requestedAt: "2026-01-20T10:00:00",
    schoolName: "St. Patrick's NS",
    from: "St. Patrick's National School, Cork",
    to: "Fota Wildlife Park, Cork",
    tripDate: "2026-03-15T09:00:00",
    passengers: 50,
    price: 450.0,
    status: "Quoted",
    type: "One Way",
  },
];
